language: node_js
node_js: stable
cache: npm

env:
  global:
    - REF=e.coding.net/wanghaoxi3000/darklab.git

branches:
  only:
    - master

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo g

after_script:
  - cd public
  - git init
  - git remote add origin https://${REF}
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://${TOKEN_NAME}:${TOKEN}@${REF}" master
  - cat index.html
# notifications:
#   email:
#     recipients:
#       - hx3000@foxmail.com
#     on_success: always
#     on_failure: always
