name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: A job to deploy blog.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true # Checkout private submodules(themes or something else).

    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
    - name: Cache node modules
      uses: actions/cache@v2.0.0
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Generate
      run: |
        npm install hexo-cli -g
        hexo generate

    - name: Uptoc Action
      uses: saltbo/uptoc@v1.4.3
      with:
        driver: cos
        region: ap-hongkong
        bucket: ${{ secrets.TCLOUD_BUCKET_ID }}
        exclude: .cache,test
        dist: public
      env:
        UPTOC_UPLOADER_AK: ${{ secrets.TCLOUD_SECRET_ID }}
        UPTOC_UPLOADER_SK: ${{ secrets.TCLOUD_SECRET_KEY }}
